# Site settings
title: Allyourgrace
email: allyourgrace@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Frontend Developer Eunhye Kim
baseurl: "http://allyourgrace.github.io" # the subpath of your site, e.g. /blog/
url: "http://allyourgrace.github.io" # the base hostname & protocol for your site
github_username:  allyourgrace

# Build settings
markdown: kramdown

paginate: 4

author: allyourgrace

gems: [jekyll-paginate]
